[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements-cloud.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python main.py --mode api --port $PORT"
